config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /bg|en/ do
    root to: 'home#index'
    get 'home/index', path: "index"
    get 'home/book', path: "book"
    get 'home/thebook', path: "thebook"
    get 'home/idea', path: "idea"
    get 'home/autor', path: "autor"
    get 'home/contacts', path: "contacts"

    get 'contacts/new'

    get 'contacts/create'

    resource :contacts, only: [:new, :create]

  end

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :about,     :validate => true
  attribute :message,   :validate => true
  attribute :nickname,  :captcha => true

  def headers
    {
      :subject => "Contact Form",
      :to => "glory.angelova@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def default_url_options
    { locale: I18n.locale }
  end

  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Съобщението не може да бъде изпратено.'
      redirect_to contacts_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    flash[:notice] = t('hello')
    @contact = Contact.new
  end

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def book
    render layout: 'books'
  end

  def thebook
  end

  def idea
  end

  def autor
  end

  def contacts
      @contact = Contact.new(params[:contact])
      @contact.request = request
      if @contact.deliver
        flash.now[:error] = nil
      else
        flash.now[:error] = 'Съобщението не може да бъде изпратено.'
        render :contacts
      end
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Съобщението не може да бъде изпратено.'
      redirect_to contacts_path
    end
    render "contacts/new"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_header.html.erb
<header class="div-header">
  <div class="container-fluid">
    <div class="inside-header">
      <div class="row">

        <div class="header-left">
          <div class = "hamburger-div">
            <i id="nav_bar_toggle" class="fa fa-bars fa-2x visible-sm visible-xs pull-right menu-hamburger navbar-toggle" aria-hidden="true"></i>
          </div>

          <nav class="navigation">
            <!-- <div id="main_nav_bar" class="nav-bar hidden-xs hidden-sm"> -->
              <ul id = "main_nav_bar" class="links-to-floor clearfix">
                <li class="menu-tag nav-toggle-li"><%= link_to t("home.menu-one"), home_index_path, id: "current_link", class: "menu-text #{current_page?(home_index_path) ? "current" : nil }" %></li>
                <li class="menu-tag nav-toggle-li"><%= link_to t("home.menu-two"), home_thebook_path, id: "current_link", class: "menu-text #{current_page?(home_thebook_path) ? "current" : nil }" %></li>
                <li class="menu-tag nav-toggle-li"><%= link_to t("home.menu-three"), home_idea_path, id: "current_link", class: "menu-text #{current_page?(home_idea_path) ? "current" : nil }" %></li>
                <li class="menu-tag nav-toggle-li"><%= link_to t("home.menu-four"), home_autor_path, id: "current_link", class: "menu-text #{current_page?(home_autor_path) ? "current" : nil }" %></li>
                <li class="menu-tag nav-toggle-li"><%= link_to t("home.menu-five"), home_contacts_path, id: "current_link", class: "menu-text #{current_page?(home_contacts_path) ? "current" : nil }" %></li>
              </ul>
            <!-- </div> -->
          </nav>
        </div>
        <div class = "header-right">
          <ul class="fb-en-ul fb-resp clearfix">
            <li class="fb-en"><%= link_to "f", "https://www.facebook.com/pchelandia", class: "f-button" %></li>
            <li class="fb-en">
              <%
                current_locale = I18n.locale
                toggle_locale  = current_locale == :en ? 'bg' : 'en'
                current_path   = url_for(params.merge(locale: toggle_locale))
              %>
              <%= link_to toggle_locale,   "#{current_path}", class: "en-button" %>
            </li>
          </ul>
        </div>
      </div>
      <div>
        <%= render 'logo' %>
      </div>
    </div>

  </div>
</header>

app/views/contacts/_logo.bg.html.erb
<%= image_tag("logo.png", id: "logo", alt: "logo") %>

app/views/contacts/_logo.en.html.erb
<%= image_tag("logo-en.png", id: "logo", alt: "logo-en") %>

app/views/contacts/_new.html.erb
<div class="form-div">
  <h3 class = "contact-title"><%= t("contact.title")%></h1>

  <%= form_for @contact do |f| %>
  <!-- <%= f.label class:"text-label" %> -->
  <br>
  <%= f.text_field :name, requested: true, class:"input-label", placeholder: t("helpers.name") %>

  <br>

  <!-- <%= f.label t ("contact.email"), class:"text-label" %> -->
  <br>
  <%= f.text_field :email, requested: true, class:"input-label", placeholder: t("helpers.email") %>

  <br>

  <!-- <%= f.label t ("contact.about"), class:"text-label" %> -->
  <br>
  <%= f.text_field :about, requested: true, class:"input-label",  placeholder: t("helpers.subject") %>

  <br>

  <!-- <%= f.label t ("contact.message"), class:"text-label" %> -->
  <br>
  <%= f.text_area :message, as: :text, class:"input-message",  placeholder: t("helpers.message") %>

  <br>

  <div class='hidden'>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname, hint: 'остави това поле празно' %>
  </div>

  <%= f.submit t ("contact.send") %>
  <% end %>

</div>

app/views/contacts/create.html.erb
<div class = "create-contact">
  <h1 class = 'create-title'><%= t ('contact.create-title') %></h1>
  <p class = "create-p"><%= t ('contact.paragraph') %></p>
  <!-- <div class="create-back-btn"><%= link_to t("contact.back"), home_contacts_path, class:"menu-text-btn" %></div> -->
</div>

app/views/contacts/new.html.erb
<h1>Contact form</h1>

<div>
  <%= form_for @contact do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name, requested: true %>

  <br>

  <%= f.label :email %><br>
  <%= f.text_field :email, requested: true %>

  <br>

  <%= f.label :about %><br>
  <%= f.text_field :about, requested: true %>

  <br>

  <%= f.label :message %><br>
  <%= f.text_area :message, as: :text %>

  <br>

  <div class='hidden'>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname, hint: 'остави това поле празно' %>
  </div>

  <br>
  <%= f.submit 'Изпрати' %>
  <% end %>

</div>

app/views/home/_cover.bg.html.erb
<%= image_tag("Cover.jpg", alt: "cover", width:"100%", height:"100%")%>

app/views/home/_page1.bg.html.erb
<%= image_tag("demo1/1.jpg", class: "picture", alt: "image01" ) %>

app/views/home/_page1.en.html.erb
<%= image_tag("demo1/1.1.jpg", class: "picture", alt: "image01" ) %>

app/views/home/_page2.bg.html.erb
<%= image_tag("demo1/2.jpg", class: "picture", alt: "image01" ) %>

app/views/home/_page2.en.html.erb
<%= image_tag("demo1/2.2.jpg", class: "picture", alt: "image01" ) %>

app/views/home/_page3.bg.html.erb
<%= image_tag("demo1/3.jpg", class: "picture", alt: "image01" ) %>

app/views/home/_page4.bg.html.erb
<%= image_tag("demo1/4.jpg", class: "picture", alt: "image01" ) %>

app/views/home/_page5.en.html.erb
<%= image_tag("demo1/5.5.jpg", class: "picture", alt: "image01" ) %>

app/views/home/book.html.erb
<div class="background-images">
  <div class="main clearfix">
    <div class="bb-custom-wrapper">
      <div id="bb-bookblock" class="bb-bookblock">
        <div class="bb-item">
          <%= render 'page1'%>
        </div>
        <div class="bb-item">
          <%= render 'page2'%>
        </div>
        <div class="bb-item">
          <%= render 'page3'%>
        </div>
        <div class="bb-item">
          <%= render 'page4'%>
        </div>
        <div class="bb-item">
          <%= render 'page5'%>
        </div>
      </div>
      <nav>
        <a id="bb-nav-first" href="#" class="bb-custom-icon bb-custom-icon-first">First page</a>
        <a id="bb-nav-prev" href="#" class="bb-custom-icon bb-custom-icon-arrow-left">Previous</a>
        <a id="bb-nav-next" href="#" class="bb-custom-icon bb-custom-icon-arrow-right">Next</a>
        <a id="bb-nav-last" href="#" class="bb-custom-icon bb-custom-icon-last">Last page</a>
      </nav>

      <%= link_to t("book-b.back"), home_thebook_path, class: "back"%>

    </div>
  </div>
</div>


<script>
  var Page = (function() {

    var config = {
        $bookBlock : $( '#bb-bookblock' ),
        $navNext : $( '#bb-nav-next' ),
        $navPrev : $( '#bb-nav-prev' ),
        $navFirst : $( '#bb-nav-first' ),
        $navLast : $( '#bb-nav-last' )
      },
      init = function() {
        config.$bookBlock.bookblock( {
          speed : 800,
          shadowSides : 0.8,
          shadowFlip : 0.7
        } );
        initEvents();
      },
      initEvents = function() {

        var $slides = config.$bookBlock.children();

        // add navigation events
        config.$navNext.on( 'click touchstart', function() {
          config.$bookBlock.bookblock( 'next' );
          return false;
        } );

        config.$navPrev.on( 'click touchstart', function() {
          config.$bookBlock.bookblock( 'prev' );
          return false;
        } );

        config.$navFirst.on( 'click touchstart', function() {
          config.$bookBlock.bookblock( 'first' );
          return false;
        } );

        config.$navLast.on( 'click touchstart', function() {
          config.$bookBlock.bookblock( 'last' );
          return false;
        } );

        // add swipe events
        $slides.on( {
          'swipeleft' : function( event ) {
            config.$bookBlock.bookblock( 'next' );
            return false;
          },
          'swiperight' : function( event ) {
            config.$bookBlock.bookblock( 'prev' );
            return false;
          }
        } );

        // add keyboard events
        $( document ).keydown( function(e) {
          var keyCode = e.keyCode || e.which,
            arrow = {
              left : 37,
              up : 38,
              right : 39,
              down : 40
            };

          switch (keyCode) {
            case arrow.left:
              config.$bookBlock.bookblock( 'prev' );
              break;
            case arrow.right:
              config.$bookBlock.bookblock( 'next' );
              break;
          }
        } );
      };

      return { init : init };

  })();

  Page.init();
</script>

app/views/home/contacts.html.erb
<div class="container">
  <div class="contact-bg-div">
    <div class = "row">
      <div class="address-all col-sm-12 col-md-7 col-lg-7">
        <div class="adress-map-div">
          <!-- <div id="one_marker" style="width:550px; height:380px;"> -->
              <!-- <iframe src="https://maps.google.com/maps?q=42.671425,23.3482661&z=18&output=embed" class="map" frameborder="0" style="border:0" allowfullscreen></iframe> -->
          <!-- </div> -->
          <h3 class="title-adress"><%= t("contact.adress") %></h3>
          <h3 class="title-adress"><%= t("contact.adress-two") %></h3>
        </div>
      </div>

      <div class="col-sm-12 col-md-5 col-lg-5">
      <%= render "contacts/new" %>
      </div>
    </div>
  </div>
</div>

app/views/home/idea.html.erb
<div class="container">
  <div class="all-four">
    <div class="all-four-wraped">
      <div class="div-one-four">
        <div class="image-div"><%= image_tag("http://3.bp.blogspot.com/-2v2xO3dkStI/U0ATYnjKs0I/AAAAAAAAEnI/JBcy5nZSuYg/s890/%25D0%25A1%25D0%259F%2B-%2B%25D0%25BB%25D0%25BE%25D0%25B3%25D0%25BE.gif", class:"image-tag", alt:"sun")%></div>
          <div class="text-all">
            <div class="text row">
              <h1 class="p-title"><%= t("idea.title") %></h1>
              <p class="p-text col-sm-12 col-md-6 col-lg-6"><%= t("idea.main") %></p>
              <p class="p-text col-sm-12 col-md-6 col-lg-6"><%= t("idea.main-two") %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div  class="center-block inner-content">
      <h1 class="first-title"><%= t ('home.html') %></h1>
      <h2 class="second-title"><%= t ('home.sub-title') %></h2>
      <p class="text-main"><%= t ('home.text-home') %></p>
      <div class="text-button"><%= link_to t("home.more-button"), home_thebook_path, class:"menu-text-btn" %></div>
    </div>
  </div>
</div>

app/views/home/show.html.erb
		<div class="container background-images">
			<!-- Top Navigation -->

			<div class="main clearfix">
				<div class="bb-custom-wrapper">
					<div id="bb-bookblock" class="bb-bookblock">
						<div class="bb-item">
							<%= image_tag("demo1/1.jpg", alt: "image01")%>
						</div>
						<div class="bb-item">
              <%= image_tag("demo1/2.jpg", alt: "image02")%>
						</div>
						<div class="bb-item">
              <%= image_tag("demo1/3.jpg", alt: "image03")%>
						</div>
						<div class="bb-item">
              <%= image_tag("demo1/4.jpg", alt: "image04")%>
						</div>
						<div class="bb-item">
              <%= image_tag("demo1/5.jpg", alt: "image05")%>
						</div>
					</div>
					<nav>
						<%= link_to "First page", id: "bb-nav-first",  class: "bb-custom-icon bb-custom-icon-first" %>
						<%= link_to "Previous", id: "bb-nav-prev", class: "bb-custom-icon bb-custom-icon-arrow-left" %>
						<%= link_to "Next", id: "bb-nav-next", class: "bb-custom-icon bb-custom-icon-arrow-right" %>
						<%= link_to "Last page", id: "bb-nav-last", class: "bb-custom-icon bb-custom-icon-last" %>
					</nav>

						<%= link_to "назад", home_index_path, class: "back"%>

				</div>
			</div>
		</div><!-- /container -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<script src="js/jquerypp.custom.js"></script>
		<script src="javascripts/jquery.bookblock.js"></script>
		<script>
			var Page = (function() {

				var config = {
						$bookBlock : $( '#bb-bookblock' ),
						$navNext : $( '#bb-nav-next' ),
						$navPrev : $( '#bb-nav-prev' ),
						$navFirst : $( '#bb-nav-first' ),
						$navLast : $( '#bb-nav-last' )
					},
					init = function() {
						config.$bookBlock.bookblock( {
							speed : 800,
							shadowSides : 0.8,
							shadowFlip : 0.7
						} );
						initEvents();
					},
					initEvents = function() {

						var $slides = config.$bookBlock.children();

						// add navigation events
						config.$navNext.on( 'click touchstart', function() {
							config.$bookBlock.bookblock( 'next' );
							return false;
						} );

						config.$navPrev.on( 'click touchstart', function() {
							config.$bookBlock.bookblock( 'prev' );
							return false;
						} );

						config.$navFirst.on( 'click touchstart', function() {
							config.$bookBlock.bookblock( 'first' );
							return false;
						} );

						config.$navLast.on( 'click touchstart', function() {
							config.$bookBlock.bookblock( 'last' );
							return false;
						} );

						// add swipe events
						$slides.on( {
							'swipeleft' : function( event ) {
								config.$bookBlock.bookblock( 'next' );
								return false;
							},
							'swiperight' : function( event ) {
								config.$bookBlock.bookblock( 'prev' );
								return false;
							}
						} );

						// add keyboard events
						$( document ).keydown( function(e) {
							var keyCode = e.keyCode || e.which,
								arrow = {
									left : 37,
									up : 38,
									right : 39,
									down : 40
								};

							switch (keyCode) {
								case arrow.left:
									config.$bookBlock.bookblock( 'prev' );
									break;
								case arrow.right:
									config.$bookBlock.bookblock( 'next' );
									break;
							}
						} );
					};

					return { init : init };

			})();
		</script>
		<script>
				Page.init();
		</script>

app/views/home/thebook.html.erb
<script src="http://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

<div class="container">
  <!-- <div id="ascensorFloor2" class="myAscensorFloor"> -->
    <div class="book-background">
      <!-- <div class="container"> -->
        <div class="row">
          <div class='col-sm-12 col-md-4 col-lg-4'>
            <div class="component">
              <ul class="align">
                <li>
                  <figure class='book'>
                    <!-- Front -->
                    <ul class='hardcover_front'>
                      <li>
                        <%= render 'cover'%>
                      </li>
                      <li></li>
                    </ul>
                     <!-- Pages -->
                    <ul class='page'>
                      <li></li>
                      <li>
                        <%= link_to t("book.see-button"), home_book_path, class: "btn" %>
                        <!-- <%= link_to t("book.order-button"), "http://www.bialobratstvo.info/%D0%BA%D0%BD%D0%B8%D0%B3%D0%B8/%D0%BD%D0%BE%D0%B2%D0%B8/%D1%86%D0%B2%D0%B5%D1%82%D0%BD%D0%B8-%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D0%B8", class: "btn btn-2" %> -->
                      </li>
                      <li></li>
                      <li></li>
                      <li></li>
                    </ul>
                     <!-- Back -->
                    <ul class='hardcover_back'>
                      <li></li>
                      <li></li>
                    </ul>
                    <ul class='book_spine'>
                      <li></li>
                      <li></li>
                    </ul>
                  </figure>
                </li>
              </ul>
            </div>
            <div class="order-btn">
              <%= link_to t("book.order-button"), "http://www.bialobratstvo.info/%D0%BA%D0%BD%D0%B8%D0%B3%D0%B8/%D0%BD%D0%BE%D0%B2%D0%B8/%D1%86%D0%B2%D0%B5%D1%82%D0%BD%D0%B8-%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D0%B8", class: "btn-2" %>
            </div>
          </div>

        <div class='col-sm-12 col-md-8 col-lg-8'>
          <figcaption>
            <h1><%= t("book.title") %></h1>
            <span><%= t("book.sub-title") %></span>
            <p><%= t("book.body") %></p>
            <p><q><%= t("book.quote") %></q></p>
          </figcaption>
        </div>
        </div>
      <!-- </div> -->
    </div>
  <!-- </div> -->

</div>

app/views/layouts/application.html.erb
  <% content_for :header do %>
   <%= render "application/header" %>
  <% end %>

  <%= render template: "layouts/base" %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pchelandia | детска книга</title>
  <meta name="keywords" content="Глория Ангелова, слънчева педагогика, пчеландия, цветни истории, чета, издателство бяло братство, езотерика, детски книжки за четене, книги за деца, нови детски книги, българска детска литература, детски книги от български автори">
  <meta name="description" content="Мечтата на малка пчелна принцеса да види пролетта я отвежда на вълшебно място. Тя попада в приказна гора, в която музиката лекува, а песента повдига духа. По пътя си среща приятел, на когото винаги може да разчита. Разбира, че търтеите не са само мързеливи и досадни, но могат да бъдат верни приятели и да те забавляват дори когато ти е най-тъжно.">
  <script src="jquery.ascensor.min.js" type="text/javascript"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script scr="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <%= favicon_link_tag "favi.png"%>
</head>
<body>
  <%= yield(:header) %>
  <%= yield %>
  <footer>
    <div class="container"><%= t ('footer.copyright') %><a class = "copyright-link" href="http://gloryangelova.com/" target="_blank">Gloria Angelova</a></div>
  </footer>
</body>
</html>

app/views/layouts/books.html.erb
<%= render template: "layouts/base" %>

app/views/layouts/mylayout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pchelandia</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script scr="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script scr="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>

  <%= favicon_link_tag "Roq.png"%>

</head>
<body>
  
<%= yield %>

  <div class="footer">
    <p class="copyright">© 2016 Цветни Истории. Всички права запазени. Създадено от Gloria Angelova</p>
  </div>

</body>

</html>